
services:

  shard1svr1:
    container_name: shard1svr1
    image: mongo:5.0.31
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip 0.0.0.0 --dbpath /data/db
    ports:
      - 50000:27018
    volumes:
      - shard1svr1:/data/db

  shard1svr2:
    container_name: shard1svr2
    image: mongo:5.0.31
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip 0.0.0.0 --dbpath /data/db
    ports:
      - 50001:27018
    volumes:
      - shard1svr2:/data/db

  shard1svr3:
    container_name: shard1svr3
    image: mongo:5.0.31
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip 0.0.0.0 --dbpath /data/db
    ports:
      - 50002:27018
    volumes:
      - shard1svr3:/data/db

volumes:
  shard1svr1: {}
  shard1svr2: {}
  shard1svr3: {}
